name = "alcove-messenger"
compatibility_date = "2026-01-01"
pages_build_output_dir = "."

[[d1_databases]]
binding = "COMMUNITY_DB"
database_name = "alcove-messenger"
database_id = "094e9f6d-b1d6-47f6-8c9a-92145f64ba79"
